### ISSUE TITLE
Cannot utilize require, only import.

### ISSUE THREAD

**Issue by CameronMunroe** [sindresorhus/is-ip#16]
It would be nice if the package supported the older `require()` standard as well as the newer `import()`. 

```
Caught exception:  Error [ERR_REQUIRE_ESM]: require() of ES Module {...}/node_modules/is-ip/index.js from {...}/src/apiv1.js not supported.
Instead change the require of index.js in {...}/src/apiv1.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/{...}/src/apiv1.js:15:14)
    at Object.<anonymous> (/{...}/index.js:48:19) {
  code: 'ERR_REQUIRE_ESM'

```

Current workaround for anyone with issues is to force release to 3.1.0.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
No plans to support CommonJS.
